version: "3.8"

services:
  digital-nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: ./
    container_name: digital-nginx
    working_dir: /etc/nginx/
    volumes:
      - ~/.ssh:/root/.ssh
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      APP_SECRET: "${APP_SECRET}"
    ports:
      - "10000:80"
    networks:
      - digital_network

  digital-backend:
    build:
      dockerfile: docker/php-fpm/Dockerfile
      context: ./
      target: local
    container_name: digital-backend
    volumes:
      - ~/.ssh:/root/.ssh
      - ./docker/php-fpm/supervisor.d/local.ini:/etc/supervisor.d/default.ini
      - .:/var/www
    environment:
      PHP_MEMORY_LIMIT: 256M
      DATABASE_URL: "mysql://root:root@digital-mysql:3306/local?charset=utf8"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - digital_network

  digital-mysql:
    image: mysql:8.0.33
    container_name: digital-mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    volumes:
      - ./docker/mysql-data:/var/lib/mysql:rw
    ports:
      - "13000:3306"
    networks:
      - digital_network

networks:
  digital_network:
    name: digital_network
    driver: bridge
