<?php

declare(strict_types=1);

return [
    'AF' => ['name' => 'Afghanistan', 'dial' => '93'],
    'AL' => ['name' => 'Albania', 'dial' => '355'],
    'DZ' => ['name' => 'Algeria', 'dial' => '213'],
    'AS' => ['name' => 'American Samoa', 'dial' => '1'],
    'AD' => ['name' => 'Andorra', 'dial' => '376'],
    'AO' => ['name' => 'Angola', 'dial' => '244'],
    'AI' => ['name' => 'Anguilla', 'dial' => '1'],
    'AG' => ['name' => 'Antigua and Barbuda', 'dial' => '1'],
    'AR' => ['name' => 'Argentina', 'dial' => '54'],
    'AM' => ['name' => 'Armenia', 'dial' => '374'],
    'AW' => ['name' => 'Aruba', 'dial' => '297'],
    'AU' => ['name' => 'Australia', 'dial' => '61'],
    'AT' => ['name' => 'Austria', 'dial' => '43'],
    'AZ' => ['name' => 'Azerbaijan', 'dial' => '994'],
    'BS' => ['name' => 'Bahamas', 'dial' => '1'],
    'BH' => ['name' => 'Bahrain', 'dial' => '973'],
    'BD' => ['name' => 'Bangladesh', 'dial' => '880'],
    'BB' => ['name' => 'Barbados', 'dial' => '1'],
    'BY' => ['name' => 'Belarus', 'dial' => '375'],
    'BE' => ['name' => 'Belgium', 'dial' => '32'],
    'BZ' => ['name' => 'Belize', 'dial' => '501'],
    'BJ' => ['name' => 'Benin', 'dial' => '229'],
    'BM' => ['name' => 'Bermuda', 'dial' => '1'],
    'BT' => ['name' => 'Bhutan', 'dial' => '975'],
    'BO' => ['name' => 'Bolivia', 'dial' => '591'],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'dial' => '387'],
    'BW' => ['name' => 'Botswana', 'dial' => '267'],
    'BR' => ['name' => 'Brazil', 'dial' => '55'],
    'BN' => ['name' => 'Brunei', 'dial' => '673'],
    'BG' => ['name' => 'Bulgaria', 'dial' => '359'],
    'BF' => ['name' => 'Burkina Faso', 'dial' => '226'],
    'BI' => ['name' => 'Burundi', 'dial' => '257'],
    'KH' => ['name' => 'Cambodia', 'dial' => '855'],
    'CM' => ['name' => 'Cameroon', 'dial' => '237'],
    'CA' => ['name' => 'Canada', 'dial' => '1'],
    'CV' => ['name' => 'Cape Verde', 'dial' => '238'],
    'KY' => ['name' => 'Cayman Islands', 'dial' => '1'],
    'CF' => ['name' => 'Central African Republic', 'dial' => '236'],
    'TD' => ['name' => 'Chad', 'dial' => '235'],
    'CL' => ['name' => 'Chile', 'dial' => '56'],
    'CN' => ['name' => 'China', 'dial' => '86'],
    'CO' => ['name' => 'Colombia', 'dial' => '57'],
    'KM' => ['name' => 'Comoros', 'dial' => '269'],
    'CG' => ['name' => 'Congo', 'dial' => '242'],
    'CR' => ['name' => 'Costa Rica', 'dial' => '506'],
    'HR' => ['name' => 'Croatia', 'dial' => '385'],
    'CU' => ['name' => 'Cuba', 'dial' => '53'],
    'CY' => ['name' => 'Cyprus', 'dial' => '357'],
    'CZ' => ['name' => 'Czech Republic', 'dial' => '420'],
    'DK' => ['name' => 'Denmark', 'dial' => '45'],
    'DJ' => ['name' => 'Djibouti', 'dial' => '253'],
    'DM' => ['name' => 'Dominica', 'dial' => '1'],
    'DO' => ['name' => 'Dominican Republic', 'dial' => '1'],
    'EC' => ['name' => 'Ecuador', 'dial' => '593'],
    'EG' => ['name' => 'Egypt', 'dial' => '20'],
    'SV' => ['name' => 'El Salvador', 'dial' => '503'],
    'EE' => ['name' => 'Estonia', 'dial' => '372'],
    'ET' => ['name' => 'Ethiopia', 'dial' => '251'],
    'FI' => ['name' => 'Finland', 'dial' => '358'],
    'FR' => ['name' => 'France', 'dial' => '33'],
    'GE' => ['name' => 'Georgia', 'dial' => '995'],
    'DE' => ['name' => 'Germany', 'dial' => '49'],
    'GH' => ['name' => 'Ghana', 'dial' => '233'],
    'GR' => ['name' => 'Greece', 'dial' => '30'],
    'GT' => ['name' => 'Guatemala', 'dial' => '502'],
    'HN' => ['name' => 'Honduras', 'dial' => '504'],
    'HK' => ['name' => 'Hong Kong', 'dial' => '852'],
    'HU' => ['name' => 'Hungary', 'dial' => '36'],
    'IS' => ['name' => 'Iceland', 'dial' => '354'],
    'IN' => ['name' => 'India', 'dial' => '91'],
    'ID' => ['name' => 'Indonesia', 'dial' => '62'],
    'IR' => ['name' => 'Iran', 'dial' => '98'],
    'IQ' => ['name' => 'Iraq', 'dial' => '964'],
    'IE' => ['name' => 'Ireland', 'dial' => '353'],
    'IL' => ['name' => 'Israel', 'dial' => '972'],
    'IT' => ['name' => 'Italy', 'dial' => '39'],
    'JP' => ['name' => 'Japan', 'dial' => '81'],
    'JO' => ['name' => 'Jordan', 'dial' => '962'],
    'KZ' => ['name' => 'Kazakhstan', 'dial' => '7'],
    'KE' => ['name' => 'Kenya', 'dial' => '254'],
    'KR' => ['name' => 'South Korea', 'dial' => '82'],
    'KW' => ['name' => 'Kuwait', 'dial' => '965'],
    'KG' => ['name' => 'Kyrgyzstan', 'dial' => '996'],
    'LV' => ['name' => 'Latvia', 'dial' => '371'],
    'LB' => ['name' => 'Lebanon', 'dial' => '961'],
    'LT' => ['name' => 'Lithuania', 'dial' => '370'],
    'LU' => ['name' => 'Luxembourg', 'dial' => '352'],
    'MY' => ['name' => 'Malaysia', 'dial' => '60'],
    'MX' => ['name' => 'Mexico', 'dial' => '52'],
    'MD' => ['name' => 'Moldova', 'dial' => '373'],
    'MC' => ['name' => 'Monaco', 'dial' => '377'],
    'ME' => ['name' => 'Montenegro', 'dial' => '382'],
    'MA' => ['name' => 'Morocco', 'dial' => '212'],
    'NL' => ['name' => 'Netherlands', 'dial' => '31'],
    'NZ' => ['name' => 'New Zealand', 'dial' => '64'],
    'NG' => ['name' => 'Nigeria', 'dial' => '234'],
    'NO' => ['name' => 'Norway', 'dial' => '47'],
    'PK' => ['name' => 'Pakistan', 'dial' => '92'],
    'PL' => ['name' => 'Poland', 'dial' => '48'],
    'PT' => ['name' => 'Portugal', 'dial' => '351'],
    'RO' => ['name' => 'Romania', 'dial' => '40'],
    'RU' => ['name' => 'Russia', 'dial' => '7'],
    'SA' => ['name' => 'Saudi Arabia', 'dial' => '966'],
    'RS' => ['name' => 'Serbia', 'dial' => '381'],
    'SG' => ['name' => 'Singapore', 'dial' => '65'],
    'SK' => ['name' => 'Slovakia', 'dial' => '421'],
    'SI' => ['name' => 'Slovenia', 'dial' => '386'],
    'ZA' => ['name' => 'South Africa', 'dial' => '27'],
    'ES' => ['name' => 'Spain', 'dial' => '34'],
    'SE' => ['name' => 'Sweden', 'dial' => '46'],
    'CH' => ['name' => 'Switzerland', 'dial' => '41'],
    'TH' => ['name' => 'Thailand', 'dial' => '66'],
    'TR' => ['name' => 'Turkey', 'dial' => '90'],
    'UA' => ['name' => 'Ukraine', 'dial' => '380'],
    'AE' => ['name' => 'United Arab Emirates', 'dial' => '971'],
    'GB' => ['name' => 'United Kingdom', 'dial' => '44'],
    'US' => ['name' => 'United States', 'dial' => '1'],
    'UY' => ['name' => 'Uruguay', 'dial' => '598'],
    'UZ' => ['name' => 'Uzbekistan', 'dial' => '998'],
    'VN' => ['name' => 'Vietnam', 'dial' => '84'],
    'ZM' => ['name' => 'Zambia', 'dial' => '260'],
    'ZW' => ['name' => 'Zimbabwe', 'dial' => '263'],
];