controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_registration:
    path: /reg
    controller: App\Controller\Customer\RegistrationController::new

user_registration_done:
    path: /compare
    controller: App\Controller\Customer\CustomerCompareController::compare

user_login:
    path: /log
    controller: App\Controller\Customer\LoginController::index

user_home:
    path: /lk
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard.html.twig

note_create:
    path: /note/create
    controller: App\Controller\Note\NoteCreateController::create

note_decrypt:
    path: /note/{noteId}/decrypt/{question}
    controller: App\Controller\Note\NoteDecryptController::decrypt
    requirements:
        question: '\w+' # Regex to ensure the question parameter only contains word characters
    defaults:
        question: 'default' # Default value if question is not provided


home:
    path:          /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'base.html.twig'

about:
    path:          /about
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'about.html.twig'

customer_creating:
    path:          /creating
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'user/creating.html.twig'


        # the response status code (default: 200)
        statusCode: 200

        # special options defined by Symfony to set the page cache
        maxAge:    86400
        sharedAge: 86400

        # whether caching should apply for client caches only
        private: true

        # optionally you can define some arguments passed to the template
        context:
            site_name: 'Di-in'
            theme: 'dark'