controllers:
    resource:
        path:    ../src/Controller/
        namespace: App\Controller
    type: attribute

user_registration:
    path:       /reg
    controller: App\Controller\Customer\RegistrationController::new

user_registration_done:
    path:       /compare
    controller: App\Controller\Customer\CustomerCompareController::compare

user_login:
    path:       /log
    controller: App\Controller\Customer\LoginController::index

user_home_1:
    path:       /lk_old
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard.html.twig

user_home:
    path:       /lk
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/index.html.twig

user_home_email:
    path:       /lk_email
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/email_first.html.twig

user_home_email_:
    path:       /lk_email_
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/email_second.html.twig

user_home_phone:
    path:       /lk_phone
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/phone_first.html.twig

user_home_phone_:
    path:       /lk_phone_
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/phone_second.html.twig

user_home_heir:
    path:       /lk_heir
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/heir.html.twig

user_home_social:
    path:       /lk_soc
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/social.html.twig

user_home_env:
    path:       /lk_env
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/envelope.html.twig

user_home_pipe:
    path:       /lk_pipe
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/pipeline.html.twig

user_home_pay:
    path:       /lk_pay
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template:    user/dashboard/payment.html.twig

user_home_ref:
    path:       /lk_ref
    defaults:
        _controller: App\Controller\Customer\ReferralController
        template:    user/dashboard/referral.html.twig

note_create:
    path:       /note/create
    controller: App\Controller\Note\NoteCreateController::create

note_edit:
    path:       /note/{noteId}/edit
    controller: App\Controller\Note\NoteEditController::edit

note_delete:
    path:       /note/{noteId}/delete
    controller: App\Controller\Note\NoteDeleteController::delete

#?? Do I need it note_decrypt ??
note_decrypt:
    path:       /note/{noteId}/decrypt/{question}
    controller: App\Controller\Note\NoteDecryptController::decrypt
    requirements:
        question: '\w+' # Regex to ensure the question parameter only contains word characters
    defaults:
        question: 'default' # Default value if question is not provided

beneficiary_create:
    path:       /beneficiary/create
    controller: App\Controller\Beneficiary\BeneficiaryCreateController::create

beneficiary_edit:
    path:       /beneficiary/{beneficiaryId}/edit
    controller: App\Controller\Beneficiary\BeneficiaryEditController::edit

beneficiary_delete:
    path: /beneficiary/{beneficiaryId}/delete
    controller: App\Controller\Beneficiary\BeneficiaryDeleteController::delete


home:
    path:       /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'home_new.html.twig'

404:
    path:       /404
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  '404.html.twig'

wait:
    path:       /wait
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'wait.html.twig'

about:
    path:       /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'about.html.twig'

contact_us:
    path:       /contact_us
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'contactUs.html.twig'

terms:
    path:       /terms
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'legal/terms.html.twig'

privacy:
    path:       /privacy
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'legal/privacy.html.twig'

refund:
    path:       /refund
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'legal/refund.html.twig'

successful_payment:
    path: /successful-payment
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'user/successful_payment.html.twig'

failed_payment:
    path: /failed-payment
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'user/failed_payment.html.twig'

checkout:
    path:       /checkout
    controller: App\Controller\Checkout\CheckoutTwigController
    defaults:
        template:  'checkout.html.twig'


customer_delete:
    path:       /customer/delete
    controller: App\Controller\Customer\CustomerDeleteController

customer_delete_verification_route:
    path:       /customer-delete/{token}
    controller: App\Controller\Customer\CustomerDeleteVerificationController

customer_cancel_deletion:
    path:       /cancel-deletion
    controller: App\Controller\Customer\CancelDeletionController

email_verification_route:
    path:       /verify-email/{token}
    controller: App\Controller\Contact\EmailVerificationController::verifyEmail

resend_verification:
    path: /resend-verification
    controller: App\Controller\Contact\ResendVerificationController::resend

wa_verification_route:
    path:       /verify-wa/{token}
    controller: App\Controller\Contact\WhatsAppVerificationController::verifyWa

social_verification_route:
    path:       /verify-social/{token}
    controller: App\Controller\Contact\SocialVerificationController::verifySocial

contact_edit:
    path:       /contact/{contactId}/edit
    controller: App\Controller\Contact\ContactEditController::edit

contact_create:
    path:       /contact/{type}/create
    controller: App\Controller\Contact\ContactCreateController::create

test_tg:
    path: /tg
    controller: App\Controller\PythonServiceController::callPythonService

pipeline_create:
    path:       /pipeline/create
    controller: App\Controller\Pipeline\PipelineCreateController::create

pipeline_edit:
    path:       /pipeline/{pipelineId}/edit
    controller: App\Controller\Pipeline\PipelineEditController::edit

change_language:
    path:       /change_language/{lang}
    controller: App\Controller\Customer\LangController::changeLanguage

forgot_pass:
    path:       /forgot_pass
    controller: App\Controller\Customer\PasswordResetController::restore

password_reset_reset:
    path: /reset-password/{token}
    controller: App\Controller\Customer\PasswordResetController::reset

cron_five_minutes:
    path: /cron/five-minutes
    controller: App\Controller\CronController::fiveMinutesCheck
    methods: [POST]

wazzup_webhook:
    path: /api/wazzup
    controller: App\Controller\Webhook\WazzupWebhookController
    methods: [POST]

email_webhook:
    path: /api/email
    controller: App\Controller\Webhook\EmailWebhookController
    methods: [POST]

payment_webhook:
    path: /api/payment
    controller: App\Controller\Webhook\PaymentWebhookController
    methods: [POST]

create_invoice:
        path: /api/create-invoice
        controller: App\Controller\Checkout\CreateInvoiceController
        methods: [POST]

beneficiary_access_note:
    path:       /secret-envelope/{token}
    controller: App\Controller\Beneficiary\BeneficiaryAccessController

customer_creating:
    path:        /creating
    controller:  Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'user/creating.html.twig'

        # the response status code (default: 200)
        statusCode: 200

        # special options defined by Symfony to set the page cache
        maxAge:    86400
        sharedAge: 86400

        # whether caching should apply for client caches only
        private: true

        # optionally you can define some arguments passed to the template
        context:
            site_name: 'Di-in'
            theme: 'dark'